### ISSUE TITLE
Followings followers model

### ISSUE THREAD

**Issue by Jma353** [cuappdev/podcast-backend#4]
How will this be stored such that we can quickly look up who follows an individual when someone posts content (relevant to feed back updates)?

**Comment by amit-mizrahi** [comment]
Thoughts on this: Currently I've restricted my attention to possible models where each user has a "followings" attribute and a "followers" attribute. We could discuss other approaches as well.

Denormalizing the feed in the "followers" attribute (storing it along with primary keys for each follower) would make things slower rather than faster. Suppose user X follows user A and user B. If user A posts something, user X's feed will have to be updated in the model for both user A _and_ user B. 

The denormalized approach would end up requiring _O(n^2)_ document accesses, since we have to access all of user A's followers (which, in this case, would include X) and all of the users that user A's followers are following (which, in this case, would include user B).

An alternative faster approach doesn't denormalize the feed attribute. Instead, it simply stores only user primary keys for both followers and followings. This will require _O(n)_ document accesses each time a user updates the feed, one for each follower. This seems like it's the fastest approach. However, there may be a _O(1)_ solution that I haven't thought of.

**Comment by Jma353** [comment]
followers_followings: 
````
ID - UUID of owning user
followers - [ follower_1_uuid, follower_2_uuid, …] 
followings - [ UUID’s of people I follow ] 
````
fetch followers 
batch update those feeds by looking up feeds that correspond to those follower’s UUID’s

**Comment by amit-mizrahi** [comment]
Separate documents for follower/following pairs:
````
UserPair:
id1 = UUID of user 1
id2 = UUID of user 2 (id2 < id1)
type = Constants.PairType.FOLLOWER | Constants.PairType.FOLLOWING
````
Need to write two `map-reduce` jobs: one that aggregates pairs of followers involving a user and one that aggregates pairs of followings involving a user.

**Comment by Jma353** [comment]
@amit-mizrahi I like the `enum` style.  Writing a switch-case statement function that we can use for formatting purposes when dropping `"type"` information into entities.  c66afd79d1fc8851987e78decf1a1342f0875422 

@hongj77 and I were thinking we'd have the following structure for the data model, all within the `followings_followers` bucket: 

### Followings 
**Key:** `Your UUID`:`Person who you follow`:following
Meant to be used to check who you follow

```` javascript 
{
  "type": "following",
  "ownerId": "id1",
  "followingId": "id2",
  "followingImageUrl": "https://goo.gl/L37gfS",
  "followingFirstName": "Joe",
  "followingLastName": "Antonakakis",
  "followingUsername": "jma353"
}
````

### Followers
**Key:** `Your UUID`:`Person following you`:follower
Meant to be used to check who is following you

````javascript 
{
  "type": "follower",
  "ownerId": "id1",
  "followerId": "id2",
  "followerImageUrl": "https://goo.gl/L37gfS",
  "followerFirstName": "Joe",
  "followerLastName": "Antonakakis",
  "followerUsername": "jma353"
}
````

The reason for the above structure is so we have data locality for our followers and followings information.  If I wanna see everyone I follow, I know that all the information will probably be on a single node given our key structure.  In addition, if I'm viewing user A's profile, checking to see if I follow that person is a key-value lookup (`My UUID`:`A's UUID`:following).  If we get a value back, we follow them, if not, we don't.  This is necessary to know quickly when viewing an individual's profile.  

The value contains a lot of user information so we can return that to front-end on them requesting a list of our followers or our followings.  In terms of `map-reduce` aggregation, your scripts look good, you might need to change some field names to fit this data model that we discussed in terms of feed updates.

**Comment by amit-mizrahi** [comment]
Sounds great. Denormalizing the first name, last name, pic and username (all the things you'd see in a follower list) is a good idea. I'll change the map reduce scripts accordingly.

Looking forward to a productive meeting tomorrow.

**Comment by Jma353** [comment]
@amit-mizrahi I fixed your models to abide to the above format: cd3c29dfddee0033adf770e8e507be795516bc78.  Feel free to fill in the details and focus on `map-reduce` aggregation

**Comment by amit-mizrahi** [comment]
Fixing schema to match what frontend requested:

    {
      "type": "following",
      "ownerId": "id1",
      "id": "id2",
      "imageUrl": "https://goo.gl/L37gfS",
      "firstName": "Joe",
      "lastName": "Antonakakis",
      "username": "jma353"
    }

    {
      "type": "follower",
      "ownerId": "id1",
      "id": "id2",
      "imageUrl": "https://goo.gl/L37gfS",
      "firstName": "Joe",
      "lastName": "Antonakakis",
      "username": "jma353"
    }

**Comment by amit-mizrahi** [comment]
Implemented.
